language: python
python:
 - "2.6"
 - "2.7"
 - "3.3"
install:
- python setup.py install
- travis_retry pip install python-coveralls
script: python setup.py nosetests
after_success: coveralls
notifications:
    email: false
    irc:
        - "irc.freenode.net#toscawidgets"
    on_success: change
    on_failure: always
